name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.7.2'  

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Set up environment variables
      env:
        DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      run: |
        echo "Database Connection String: $DB_CONNECTION_STRING"